### ISSUE TITLE
Uso de Sustom Table

### ISSUE THREAD

**Issue by MaxiMarolda** [MaxiMarolda/259_Brewing_Co#34]
Pablo, acabo de implementar la custom table en el informde barriles y si bien lo pude hacer funcionar, recien muestra los datos despues de salir y volver a entrar. Si bien hace el GET apenas entra y lo repite unos segundos despues te sale un cartel que dice  no data. Si elegis otra solapa del menu y vovles a elegir barriles ahí si te lo muestra...

**Comment by BarberoPablo** [comment]
Si, hay que hacer un rederisado condicional para que muestre bien la data

**Comment by MaxiMarolda** [comment]
Ahí estuve revisando el cambio y vi que estaba usando mal el renderizado al no invocar la variable del estado que tenía la información: {handleData} por eso no renderizaba la info ya que no actualizaba al cambiar la información.
